/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AppTest {
    private static final Logger LOGGER = LoggerFactory.getLogger(AppTest.class);

    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    static String csvSafeString(String str) {
        if (str != null) {
            return "\"" + str.replaceAll("\"", "\"\"") + "\"";
        } else {
            return "";
        }
    }

    @Test
    public void name() throws Exception {
        LOGGER.debug("Debug logger");
        assertTrue(true);
    }

    @Test
    public void testCsvSafeString() {
        LOGGER.error("ERROR STRING");
        assertTrue(true);
        //assertEquals("\"string with, and \"\"quotes\"\"\"", csvSafeString("string with, and \"quotes\""));
        //assertEquals("123", csvSafeString("test_match_returnExpectedMatch_whenPatternAndTextProvided[match should return true when pattern \"*a\\Qb*\" and text \"a\\Qb\" provided]"));
    }
}
