/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.nio.file.Paths;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    static String csvSafeString(String str) {
        if (str != null) {
            return "\"" + str.replaceAll("\"", "\"\"") + "\"";
        } else {
            return "";
        }
    }

    @Test
    public void name() throws Exception {
        Paths.get("some*sad***asd00");
    }

    @Test
    public void testCsvSafeString() {
        //assertEquals("\"string with, and \"\"quotes\"\"\"", csvSafeString("string with, and \"quotes\""));
        //assertEquals("123", csvSafeString("test_match_returnExpectedMatch_whenPatternAndTextProvided[match should return true when pattern \"*a\\Qb*\" and text \"a\\Qb\" provided]"));
    }
}
